version: "3.7"

services:
  database:
    image: postgres
    container_name: database-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=datewithDB
      - POSTGRES_DB=datewith
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: date-with
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
